package login;


import subject.*;
import exam.*;
import form.*;
import account.accounthome;
import student.studenthome;
import teacher.teacherhome;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ben
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Jmenuhome = new javax.swing.JMenuBar();
        Home = new javax.swing.JMenu();
        Student = new javax.swing.JMenu();
        Form = new javax.swing.JMenu();
        jmnuformone = new javax.swing.JMenuItem();
        jmnuformtwo = new javax.swing.JMenuItem();
        jmnuformthree = new javax.swing.JMenuItem();
        jmnuformfour = new javax.swing.JMenuItem();
        Teacher = new javax.swing.JMenu();
        Subject = new javax.swing.JMenu();
        Exam = new javax.swing.JMenu();
        jmnuexams = new javax.swing.JMenuItem();
        jmnumarks = new javax.swing.JMenuItem();
        jmnureport = new javax.swing.JMenu();
        jmnuresults = new javax.swing.JMenuItem();
        jmnustudentreport = new javax.swing.JMenuItem();
        Accounts = new javax.swing.JMenu();
        Help = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOME");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/sch.jpg"))); // NOI18N

        Jmenuhome.setMinimumSize(new java.awt.Dimension(56, 30));
        Jmenuhome.setPreferredSize(new java.awt.Dimension(317, 30));

        Home.setText("Home");
        Jmenuhome.add(Home);

        Student.setText("Student");
        Student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentMouseClicked(evt);
            }
        });
        Jmenuhome.add(Student);

        Form.setText("Form");
        Form.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FormMouseClicked(evt);
            }
        });

        jmnuformone.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jmnuformone.setText("Form One");
        jmnuformone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmnuformoneMouseClicked(evt);
            }
        });
        jmnuformone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuformoneActionPerformed(evt);
            }
        });
        Form.add(jmnuformone);

        jmnuformtwo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jmnuformtwo.setText("Form Two");
        jmnuformtwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmnuformtwoMouseClicked(evt);
            }
        });
        jmnuformtwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuformtwoActionPerformed(evt);
            }
        });
        Form.add(jmnuformtwo);

        jmnuformthree.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jmnuformthree.setText("Form Three");
        jmnuformthree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuformthreeActionPerformed(evt);
            }
        });
        Form.add(jmnuformthree);

        jmnuformfour.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jmnuformfour.setText("Form Four");
        jmnuformfour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuformfourActionPerformed(evt);
            }
        });
        Form.add(jmnuformfour);

        Jmenuhome.add(Form);

        Teacher.setText("Teacher");
        Teacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TeacherMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TeacherMouseEntered(evt);
            }
        });
        Jmenuhome.add(Teacher);

        Subject.setText("Subject");
        Subject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubjectMouseClicked(evt);
            }
        });
        Jmenuhome.add(Subject);

        Exam.setText("Examinatons");
        Exam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExamMouseClicked(evt);
            }
        });

        jmnuexams.setText("Exams");
        jmnuexams.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmnuexamsMouseClicked(evt);
            }
        });
        jmnuexams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuexamsActionPerformed(evt);
            }
        });
        Exam.add(jmnuexams);

        jmnumarks.setText("Marks");
        jmnumarks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmnumarksMouseClicked(evt);
            }
        });
        jmnumarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnumarksActionPerformed(evt);
            }
        });
        Exam.add(jmnumarks);

        jmnureport.setText("Reports");

        jmnuresults.setText("Class Report");
        jmnuresults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuresultsActionPerformed(evt);
            }
        });
        jmnureport.add(jmnuresults);

        jmnustudentreport.setText("Student Report");
        jmnustudentreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnustudentreportActionPerformed(evt);
            }
        });
        jmnureport.add(jmnustudentreport);

        Exam.add(jmnureport);

        Jmenuhome.add(Exam);

        Accounts.setText("Accounts");
        Accounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountsMouseClicked(evt);
            }
        });
        Jmenuhome.add(Accounts);

        Help.setText("Help");
        Jmenuhome.add(Help);

        setJMenuBar(Jmenuhome);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel1)
                .addContainerGap(224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void StudentMouseClicked(java.awt.event.MouseEvent evt) {                                     
        try {
            // TODO add your handling code here:
            new studenthome().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }                                    

    private void FormMouseClicked(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
        //new formhome().setVisible(true);
    }                                 

    private void TeacherMouseEntered(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void TeacherMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        new teacherhome().setVisible(true);
    }                                    

    private void SubjectMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        new subjecthome().setVisible(true);
    }                                    

    private void ExamMouseClicked(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
       
    }                                 

    private void AccountsMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        new accounthome().setVisible(true);
    }                                     

    private void jmnuformoneActionPerformed(java.awt.event.ActionEvent evt) {                                            

        try {
            // TODO add your handling code here:
            studenthome st= new studenthome();
            st.populate("select * from student where class_id=1");
            st.class_id=1;
            st.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }                                           

    private void jmnuformoneMouseClicked(java.awt.event.MouseEvent evt) {                                         
        
        
    }                                        

    private void jmnuformtwoMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jmnuformtwoActionPerformed(java.awt.event.ActionEvent evt) {                                            
        try {
            // TODO add your handling code here:
            studenthome st= new studenthome();
            st.populate("select * from student where class_id=2");
            st.class_id=2;
            st.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                           

    private void jmnuformthreeActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            studenthome st= new studenthome();
            st.populate("select * from student where class_id=3");
            st.class_id=3;
            st.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                             

    private void jmnuformfourActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            studenthome st= new studenthome();
            st.populate("select * from student where class_id=4");
            st.class_id=4;
            st.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                            

    private void jmnuexamsMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
         
    }                                      

    private void jmnumarksMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
         
    }                                      

    private void jmnumarksActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        marks mk=new marks();
        ResultSet rt;
        rt=new subject().viewsubject();
        try {
            while(rt.next()){
                mk.jcbosubject.addItem(rt.getString("sub_name"));                
            }
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }        
        
        rt=new form().getform();
        try {
            while(rt.next()){
                mk.jcboclass.addItem(rt.getString("class_name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        mk.setVisible(true);
    }                                         

    private void jmnuexamsActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        new examhome().setVisible(true);
    }                                         

    private void jmnuresultsActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        new results().setVisible(true);
    }                                           

    private void jmnustudentreportActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        new studentreport().setVisible(true);
    }                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenu Accounts;
    private javax.swing.JMenu Exam;
    private javax.swing.JMenu Form;
    private javax.swing.JMenu Help;
    private javax.swing.JMenu Home;
    private javax.swing.JMenuBar Jmenuhome;
    private javax.swing.JMenu Student;
    private javax.swing.JMenu Subject;
    private javax.swing.JMenu Teacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jmnuexams;
    private javax.swing.JMenuItem jmnuformfour;
    private javax.swing.JMenuItem jmnuformone;
    private javax.swing.JMenuItem jmnuformthree;
    private javax.swing.JMenuItem jmnuformtwo;
    private javax.swing.JMenuItem jmnumarks;
    private javax.swing.JMenu jmnureport;
    private javax.swing.JMenuItem jmnuresults;
    private javax.swing.JMenuItem jmnustudentreport;
    // End of variables declaration                   
}
